name: pipeline

on:
  push:
    branches:
      - main

env:
  DEFAULT_BRANCH: main
  DEFAULT_BRANCH_ENVIRONMENT: dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: https://npm.pkg.github.com
      - name: Install Dependencies
        run: |
          npm i -g yarn
          cd ui
          yarn install
          yarn bootstrap
      - name: Build
        run: |
          cd ui/packages/myapp
          cp ../../.env.ci .env
          rm .env.local
          cd ../..
          CI=false yarn build:${{ matrix.command }}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Upload Build to S3 Build Bucket
        run: |
          BUILD_BUCKET=$(aws ssm get-parameter --name abc/efg/ --query 'Parameter.Value' --output text)
          aws s3 sync ./ui/packages/myapp/build "s3://${BUILD_BUCKET}/${{ needs.config.outputs.ref }}/${{ matrix.name }}/" --delete
          aws s3 sync ./ui/packages/myapp/build "s3://${BUILD_BUCKET}/${{ needs.config.outputs.commit-sha }}/${{ matrix.name }}/" --delete
